apiVersion: v1
kind: Service
metadata:
  name: wordpress-svc
  labels:
    app: wordpress
spec:
  type: NodePort
  selector:
    app: wordpress
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31789
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deplo
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
      - image: wordpress:5.1.1-php7.3-apache
        name: wordpress
        ports:
        - containerPort: 80
          name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: wp-mysqlsvc
        - name: WORDPRESS_DB_USER
          value: admin
        - name: WORDPRESS_DB_PASSWORD
          value: minad
        - name: WORDPRESS_DB_NAME
          value: wdpmy
        - name: WORDPRESS_DEBUG
          value: "1"
        volumeMounts:
        - name: mywp-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: mywp-persistent-storage
        persistentVolumeClaim:
          claimName: mywp-persistent-storage
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: wordpress-deplo
  namespace: default
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: wordpress-deplo
  targetCPUUtilizationPercentage: 50
