apiVersion: v1
kind: Service
metadata:
  name: nginx-b
  labels:
    app: nginx-b
spec:
  type: NodePort
  selector:
    app: nginx-b
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-b
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx-b
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-b
  namespace: default
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-b
  targetCPUUtilizationPercentage: 50
